### ISSUE TITLE
Issue with for loops

### ISSUE THREAD

**Issue by Partixel** [stravant/LuaMinify#13]
In some cases
```lua
for i = #ops, 1, -1 do
```
is minified to
```lua
for i = #i, 1, -1 do
```
Which causes issues for obvious reasons.

**Comment by Partixel** [comment]
The obvious reasons being the table now named i is replaced with the number in the for loop

**Comment by mlnlover11** [comment]
(from commit message)

Fixed by performing obfuscation of variables in NumericForStatement (which should have happened anyway). 




Verified by running this script (1,000,000 attempts) a few times:

```
for i = 1,1000000 do
	local st, ast = ParseLua('local table_ = { } for i = #table_,1,-1 do print(table_[i]) end')
	if not st then error(ast) end
	local m = Format_Mini(ast)
	--print("mini: ", m)
	if m then
		local a = m:gmatch("local i")()
		local b = m:gmatch("for i")()
		if a and b and a == b then
			print("They both contain 'i':", m)
			break
		end
	end
end
```
