### ISSUE TITLE
Linear list of tokens

### ISSUE THREAD

**Issue by LoganDark** [stravant/LuaMinify#19]
Currently, LexLua returns a large list full of tokens, each token potentially containing more lists of tokens, for example LeadingWhite full of more tokens that have to be plucked out manually and all sorts of weird things like that. Additionally, the order of LeadingWhite _cannot be relied on by index_ (not even reversed), as I figured out earlier (see issue #18). Also, comments are preserved incorrectly in LeadingWhite (#20).

I'm looking to get a list containing tokens in the order they are encountered. That means by looping through the list and adding up the `Data` of each token, I'll be able to reconstruct the original input string passed to LexLua exactly.

Is there a ready-made function to create that list for me? If not, how would I create such a function?

**Comment by LoganDark** [comment]
I ended up rewriting the lexer from scratch myself. I could share the code if anyone's interested.

**Comment by tst2005** [comment]
@LoganDark : I'm always interested by Lexer/Parser :D

**Comment by LoganDark** [comment]
https://pastebin.com/edyuQ5xY

**Comment by tst2005** [comment]
Can you publish him in a repository ? with LICENSE etc ?

**Comment by LoganDark** [comment]
https://github.com/LoganDark/lua-lexer

**Comment by tst2005** [comment]
thanks!
