### ISSUE TITLE
Whitespace bug?

### ISSUE THREAD

**Issue by LoganDark** [stravant/LuaMinify#20]
Okay, I swear, this time, I found a real issue, and I'm not just ranting about how simple it seems but how hard actually it is to reconstruct the input string from the output of LexLua.

![image](https://user-images.githubusercontent.com/4723091/34915462-1655362c-f8dc-11e7-83f9-d7a219eafa7a.png)
Feeding this into LexLua, I get this:
![image](https://user-images.githubusercontent.com/4723091/34915453-eca47e3c-f8db-11e7-8db7-31ac1275fca5.png)
Surely it's a bug. The two comments are supposed to be separate. And they are in the input string, with whitespace between them. But the comments appear joined together in the list of tokens, and the whitespace between/after them is out of order.

This goes with #18/#19. Lots of whitespace/comment bugs here.

**Comment by LoganDark** [comment]
@mlnlover11 you seem to be the most active contributor here (and the one that implemented LeadingWhite), take a look please?

**Comment by NotAFile** [comment]
Good luck getting anyone to respond, my PR (#17) has been sitting here for 1,5 years now :)

**Comment by LoganDark** [comment]
Yeah.. it seems like they've all disappeared. Maybe this issue will never get fixed. And it's a pretty important issue.

**Comment by LoganDark** [comment]
I ended up rewriting the lexer from scratch myself. I could share the code if anyone's interested.

**Comment by NotAFile** [comment]
please do!

**Comment by LoganDark** [comment]
https://pastebin.com/edyuQ5xY

Have fun.
